import { Summary, TimelineEvent, Message, Media, POI, Case } from './types';

export const mockCases: Case[] = [
  {
    id: '14523',
    device_owner: "John Doe's iPhone",
    extraction_date: '2025-12-01',
  },
];

export const mockSummary: Summary = {
  case_id: '14523',
  device_owner: "John Doe's iPhone",
  extraction_date: '2025-12-01',
  summary: {
    total_messages: 8742,
    total_contacts: 156,
    total_media: 3421,
    flagged_media: 34,
    suspicious_messages: 127,
    poi_count: 8,
  },
  top_pois: [
    {
      id: 'c_123',
      name: 'Alice Martinez',
      phone: '+1234567890',
      email: 'alice.m@email.com',
      score: 87,
      rank: 1,
      feature_breakdown: {
        total_messages: 89,
        suspicious_msg_count: 23,
        flagged_media_assoc: 8,
        time_anomaly_score: 0.71,
        communication_frequency: 4.2,
        unusual_hour_pct: 0.34,
      },
      evidence_refs: {
        message_ids: ['msg_4521', 'msg_4567'],
        media_ids: ['m_1234'],
        event_ids: ['evt_001'],
      },
      first_contact: '2025-09-12',
      last_contact: '2025-11-28',
      contact_network: [
        { id: 'c_456', name: 'John Doe', message_count: 45 },
        { id: 'c_789', name: 'Mike Johnson', message_count: 12 },
      ],
    },
    {
      id: 'c_456',
      name: 'Mike Johnson',
      phone: '+0987654321',
      score: 75,
      rank: 2,
      feature_breakdown: {
        total_messages: 67,
        suspicious_msg_count: 12,
        flagged_media_assoc: 3,
        time_anomaly_score: 0.45,
        communication_frequency: 3.1,
        unusual_hour_pct: 0.15,
      },
      evidence_refs: {
        message_ids: ['msg_4521'],
        media_ids: [],
        event_ids: [],
      },
      first_contact: '2025-08-01',
      last_contact: '2025-11-25',
      contact_network: [
        { id: 'c_123', name: 'Alice Martinez', message_count: 12 },
      ],
    },
    {
      id: 'c_789',
      name: 'Sarah Connor',
      phone: '+1122334455',
      score: 68,
      rank: 3,
      feature_breakdown: {
        total_messages: 34,
        suspicious_msg_count: 7,
        flagged_media_assoc: 5,
        time_anomaly_score: 0.38,
        communication_frequency: 1.9,
        unusual_hour_pct: 0.10,
      },
      evidence_refs: {
        message_ids: [],
        media_ids: ['m_5678'],
        event_ids: [],
      },
      first_contact: '2025-07-15',
      last_contact: '2025-11-20',
      contact_network: [],
    },
  ],
  flagged_media_snapshot: [
    {
      id: 'm_1234',
      timestamp: '2025-11-20T11:15:00Z',
      thumbnail_url: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=200&h=200&fit=crop',
      file_name: 'IMG_4521.jpg',
      file_size: 2457600,
      sha256: 'a3f5b8c2d1e4f7g9...',
      source_app: 'WhatsApp',
      labels: [
        { label: 'nsfw', confidence: 0.94, model: 'vision_classifier_v3' },
      ],
      risk_level: 'critical',
      linked_contacts: [
        { id: 'c_123', name: 'Alice Martinez', phone: '+1234567890' },
      ],
      linked_messages: [],
    },
    {
      id: 'm_5678',
      timestamp: '2025-11-18T09:30:00Z',
      thumbnail_url: 'https://images.pexels.com/photos/3862657/pexels-photo-3862657.jpeg?w=200&h=200&fit=crop',
      file_name: 'weapon.jpg',
      file_size: 1890234,
      sha256: 'b4e6c9d3f2g5h8i0...',
      source_app: 'WhatsApp',
      labels: [
        { label: 'weapon', confidence: 0.87, model: 'vision_classifier_v3' },
      ],
      risk_level: 'high',
      linked_contacts: [
        { id: 'c_789', name: 'Sarah Connor', phone: '+1122334455' },
      ],
      linked_messages: [],
    },
    {
      id: 'm_9012',
      timestamp: '2025-11-16T14:20:00Z',
      thumbnail_url: 'https://images.pexels.com/photos/443773/pexels-photo-443773.jpeg?w=200&h=200&fit=crop',
      file_name: 'IMG_4489.jpg',
      file_size: 3120456,
      sha256: 'c5f7d0e4g3h6i9j1...',
      source_app: 'Telegram',
      labels: [
        { label: 'nsfw', confidence: 0.91, model: 'vision_classifier_v3' },
      ],
      risk_level: 'critical',
      linked_contacts: [
        { id: 'c_123', name: 'Alice Martinez', phone: '+1234567890' },
      ],
      linked_messages: [],
    },
    {
      id: 'm_3456',
      timestamp: '2025-11-14T16:45:00Z',
      thumbnail_url: 'https://images.pexels.com/photos/6724534/pexels-photo-6724534.jpeg?w=200&h=200&fit=crop',
      file_name: 'IMG_4412.jpg',
      file_size: 2678900,
      sha256: 'd6g8e1f5h4i7j0k2...',
      source_app: 'SMS',
      labels: [
        { label: 'violence', confidence: 0.76, model: 'vision_classifier_v3' },
      ],
      risk_level: 'high',
      linked_contacts: [
        { id: 'c_999', name: 'Unknown', phone: '+9876543210' },
      ],
      linked_messages: [],
    },
    {
      id: 'm_7890',
      timestamp: '2025-11-12T19:00:00Z',
      thumbnail_url: 'https://images.pexels.com/photos/4974920/pexels-photo-4974920.jpeg?w=200&h=200&fit=crop',
      file_name: 'IMG_4356.jpg',
      file_size: 1945670,
      sha256: 'e7h9f2g6i5j8k1l3...',
      source_app: 'WhatsApp',
      labels: [
        { label: 'nsfw', confidence: 0.88, model: 'vision_classifier_v3' },
      ],
      risk_level: 'high',
      linked_contacts: [
        { id: 'c_456', name: 'Mike Johnson', phone: '+0987654321' },
      ],
      linked_messages: [],
    },
    {
      id: 'm_1111',
      timestamp: '2025-11-10T12:30:00Z',
      thumbnail_url: 'https://images.pexels.com/photos/3714896/pexels-photo-3714896.jpeg?w=200&h=200&fit=crop',
      file_name: 'IMG_4267.jpg',
      file_size: 2234567,
      sha256: 'f8i0g3h7j6k9l2m4...',
      source_app: 'Signal',
      labels: [
        { label: 'weapon', confidence: 0.82, model: 'vision_classifier_v3' },
      ],
      risk_level: 'high',
      linked_contacts: [
        { id: 'c_789', name: 'Sarah Connor', phone: '+1122334455' },
      ],
      linked_messages: [],
    },
  ],
  timeline_preview: [
    {
      id: 'evt_001',
      timestamp: '2025-11-15T14:34:00Z',
      type: 'message',
      label: 'Suspicious Message Exchange',
      suspicious: true,
      risk_level: 'high',
      participants: ['Alice Martinez', 'John Doe'],
      preview: 'meet at usual spot tomorrow',
      explain: {
        rules_triggered: ['keyword:location_vague', 'pattern:arranged_meeting'],
        confidence: 0.78,
        model: 'pattern_detector_v2',
      },
      evidence_refs: {
        message_ids: ['msg_4521'],
        media_ids: [],
        contact_ids: ['c_123', 'c_456'],
      },
    },
    {
      id: 'evt_002',
      timestamp: '2025-11-20T11:12:00Z',
      type: 'media_flag',
      label: 'Critical NSFW Content Detected',
      suspicious: true,
      risk_level: 'critical',
      preview_thumbnail: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=100&h=100&fit=crop',
      explain: {
        labels: ['nsfw'],
        confidence: 0.94,
        model: 'vision_classifier_v3',
      },
      evidence_refs: {
        message_ids: [],
        media_ids: ['m_1234'],
        contact_ids: ['c_123'],
      },
    },
    {
      id: 'evt_003',
      timestamp: '2025-11-28T03:45:00Z',
      type: 'message',
      label: 'Unusual Late-Night Activity',
      suspicious: true,
      risk_level: 'medium',
      preview: 'cant talk now need to lay low for a while',
      explain: {
        rules_triggered: ['timing:late_night', 'keyword:evasion'],
        confidence: 0.65,
        model: 'pattern_detector_v2',
      },
      evidence_refs: {
        message_ids: ['msg_9999'],
        media_ids: [],
        contact_ids: ['c_123'],
      },
    },
  ],
};

export const mockMessages: Message[] = [
  {
    id: 'msg_4521',
    timestamp: '2025-11-15T14:34:00Z',
    sender_id: 'c_123',
    sender_name: 'Alice Martinez',
    recipient_id: 'c_456',
    recipient_name: 'John Doe',
    text: 'meet at usual spot tomorrow',
    suspicious: true,
    risk_level: 'high',
    rules_triggered: [
      {
        rule: 'keyword:location_vague',
        description: 'Vague location reference',
        confidence: 0.82,
      },
      {
        rule: 'pattern:arranged_meeting',
        description: 'Arranged meeting pattern',
        confidence: 0.75,
      },
    ],
    cluster_id: 'C42',
    cluster_label: 'Suspicious meeting arrangements',
    media_ids: [],
    source_app: 'WhatsApp',
  },
  {
    id: 'msg_4522',
    timestamp: '2025-11-15T14:41:00Z',
    sender_id: 'c_456',
    sender_name: 'John Doe',
    recipient_id: 'c_123',
    recipient_name: 'Alice Martinez',
    text: 'ok see you there',
    suspicious: false,
    rules_triggered: [],
    media_ids: [],
    source_app: 'WhatsApp',
  },
  {
    id: 'msg_4567',
    timestamp: '2025-11-20T11:15:00Z',
    sender_id: 'c_123',
    sender_name: 'Alice Martinez',
    recipient_id: 'c_456',
    recipient_name: 'John Doe',
    text: '[Image]',
    suspicious: true,
    risk_level: 'critical',
    rules_triggered: [
      {
        rule: 'media:nsfw_detected',
        description: 'NSFW content detected',
        confidence: 0.94,
      },
    ],
    cluster_id: 'C43',
    media_ids: ['m_1234'],
    source_app: 'WhatsApp',
  },
  {
    id: 'msg_9999',
    timestamp: '2025-11-28T03:45:00Z',
    sender_id: 'c_123',
    sender_name: 'Alice Martinez',
    recipient_id: 'c_456',
    recipient_name: 'John Doe',
    text: 'cant talk now need to lay low for a while',
    suspicious: true,
    risk_level: 'medium',
    rules_triggered: [
      {
        rule: 'timing:late_night',
        description: 'Communication during unusual hours',
        confidence: 0.71,
      },
      {
        rule: 'keyword:evasion',
        description: 'Evasion language detected',
        confidence: 0.64,
      },
    ],
    media_ids: [],
    source_app: 'Signal',
  },
];

export const mockTimeline: TimelineEvent[] = [
  {
    id: 'evt_001',
    timestamp: '2025-11-15T14:34:00Z',
    type: 'message',
    label: 'Suspicious Message Exchange',
    suspicious: true,
    risk_level: 'high',
    participants: ['Alice Martinez', 'John Doe'],
    preview: 'meet at usual spot tomorrow',
    explain: {
      rules_triggered: ['keyword:location_vague', 'pattern:arranged_meeting'],
      confidence: 0.78,
      model: 'pattern_detector_v2',
    },
    evidence_refs: {
      message_ids: ['msg_4521'],
      media_ids: [],
      contact_ids: ['c_123', 'c_456'],
    },
  },
  {
    id: 'evt_002',
    timestamp: '2025-11-20T11:12:00Z',
    type: 'media_flag',
    label: 'Flagged Media Uploaded',
    suspicious: true,
    risk_level: 'critical',
    preview_thumbnail: 'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?w=100&h=100&fit=crop',
    explain: {
      labels: ['nsfw'],
      confidence: 0.94,
      model: 'vision_classifier_v3',
    },
    evidence_refs: {
      message_ids: [],
      media_ids: ['m_1234'],
      contact_ids: ['c_123'],
    },
  },
  {
    id: 'evt_003',
    timestamp: '2025-11-28T03:45:00Z',
    type: 'message',
    label: 'Unusual Late-Night Activity',
    suspicious: true,
    risk_level: 'medium',
    preview: 'cant talk now need to lay low for a while',
    explain: {
      rules_triggered: ['timing:late_night', 'keyword:evasion'],
      confidence: 0.65,
      model: 'pattern_detector_v2',
    },
    evidence_refs: {
      message_ids: ['msg_9999'],
      media_ids: [],
      contact_ids: ['c_123'],
    },
  },
];
